global using System.Collections.Immutable;
global using System.Windows.Input;
global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using I4Gerencia.Business.Models;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Localization;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using Microsoft.UI.Xaml;
global using Microsoft.UI.Xaml.Controls;
global using Microsoft.UI.Xaml.Media;
global using Microsoft.UI.Xaml.Navigation;
global using Uno.UI;
global using Windows.ApplicationModel;
global using Windows.Networking.Connectivity;
global using Windows.Storage;
global using ApplicationExecutionState = Windows.ApplicationModel.Activation.ApplicationExecutionState;

global using CommunityToolkit.Mvvm.Messaging;
global using I4Gerencia.Models;
global using I4Gerencia.Services.AppEnvironment;
//global using I4Gerencia.Services.Home;
global using I4Gerencia.Services.Install;
//global using I4Gerencia.Services.Login;
//global using I4Gerencia.Services.Menu;
//global using I4Gerencia.Services.Panel;
//global using I4Gerencia.Services.Pizarra;
global using I4Gerencia.Services.RepositorySQL;
global using I4Gerencia.Services.Settings;
global using I4Gerencia.ViewModels;
global using I4Gerencia.Views;
global using I4Kernel.Common;
global using I4Kernel.Services;
global using I4Kernel.Services.Settings;
global using I4SQL.Services;
global using Uno.Extensions;
global using static I4Kernel.Common.Enum;

